### ISSUE TITLE
CdrRequest.js - 

### ISSUE THREAD

**Issue by space7panda** [VoicenterTeam/VoicenterWebSDK#16]
`let ivrArray = JSON.parse(this.request.body.IVR);`

```
1|index  | Failed parse IVR list of cdr  SyntaxError: Unexpected token o in JSON at position 1
1|index  |     at JSON.parse (<anonymous>)
1|index  |     at CdrRequest.ParseRequest (/home/ivr-proxy/ivr-proxy/node_modules/voicenter-web-sdk/libs/CdrRequest.js:88:44)
1|index  |     at Object.cdrHandler (/home/ivr-proxy/ivr-proxy/node_modules/voicenter-web-sdk/routes/Cdr.js:15:26)
1|index  |     at preHandlerCallback (/home/ivr-proxy/ivr-proxy/node_modules/fastify/lib/handleRequest.js:117:30)
1|index  |     at preValidationCallback (/home/ivr-proxy/ivr-proxy/node_modules/fastify/lib/handleRequest.js:103:5)
1|index  |     at handler (/home/ivr-proxy/ivr-proxy/node_modules/fastify/lib/handleRequest.js:69:5)
1|index  |     at done (/home/ivr-proxy/ivr-proxy/node_modules/fastify/lib/contentTypeParser.js:115:7)
1|index  |     at Parser.defaultJsonParser [as fn] (/home/ivr-proxy/ivr-proxy/node_modules/fastify/lib/contentTypeParser.js:206:5)
1|index  |     at IncomingMessage.onEnd (/home/ivr-proxy/ivr-proxy/node_modules/fastify/lib/contentTypeParser.js:185:25)
1|index  |     at IncomingMessage.emit (events.js:228:7)
1|index  | IVR list [
1|index  |   {
1|index  |     layer_id: 137537,
1|index  |     layer_name: 'Bohdan + Valeriy',
1|index  |     layer_number: 0,
1|index  |     Dtmf: 0,
1|index  |     dtmf_order: 1
1|index  |   }
1|index  | ]
```

**Comment by space7panda** [comment]
Fixed inf refac branch
