### ISSUE TITLE
CallRequest.js

### ISSUE THREAD

**Issue by space7panda** [VoicenterTeam/VoicenterWebSDK#17]
`responseObj=this.action.GetOutput();`

```
1|index  | TypeError: Cannot read property 'GetOutput' of null
1|index  |     at CallRequest.Execute (/home/ivr-proxy/ivr-proxy/node_modules/voicenter-web-sdk/libs/CallRequest.js:102:33)
1|index  |     at CallRequest.DoCallLogic (/home/ivr-proxy/ivr-proxy/node_modules/voicenter-web-sdk/libs/CallRequest.js:78:28)
1|index  |     at processTicksAndRejections (internal/process/task_queues.js:94:5)
1|index  |     at async Object.ivrHandler (/home/ivr-proxy/ivr-proxy/node_modules/voicenter-web-sdk/routes/Ivr.js:14:5)
```

**Comment by dmitrysam88** [comment]
It's business logic issue, logic developer must call one of three methods (dial, goToLayer, say) in end of his logic.
